port

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -88,8 +88,10 @@ jobs:
          
       - name: Stop and remove container if running
         run: |
-         docker ps -q --filter "name=fastapi" | grep -q . && docker stop texts && docker rm -fv texts
-       
+          echo "Checking running containers:"
+          docker ps -a
+          docker ps -q --filter "name=fastapi" | grep -q . && echo "Container found, stopping and removing 'texts'" && docker stop texts && docker rm -fv texts || echo "No matching container found or failed to stop/remove."
+
       - name: Run Docker Image to serve users
         run: |
          docker run -d -p 8080:8080 --name=fastapi -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}'  ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
